apiVersion: apps/v1
kind: Deployment
metadata:
  name: eco-score
  labels:
    app: eco-score
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: eco-score
        image: fhkiel/ecoscore
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        image: fhkiel/ecoscore